### ISSUE TITLE
Incorrect credits

### ISSUE THREAD

**Issue by xKiraiChan** [Rafacasari/DiscordMute#6]
https://github.com/Rafacasari/DiscordMute/blob/main/DiscordMute.cs#L59

`https://github.com/ImStellar/Stellarmojis/blob/171c91c99cbcafde58d8afd898dd7ef0ec00603f/Stemojis/Kirai/WingAPI.cs#L24`
Should be corrected to
`https://github.com/xKiraiChan/WingAPI/blob/master/WingAPI.cs#L30-L34`

**Comment by Rafacasari** [comment]
Sorry about that and for late response, but now I think is correct! 
Thanks for report and thank you for the code, I was having problems with GameObject.Find and your code saved me.
